// Generated by https://www.convertjson.com/xml-to-json.htm

export interface BibliotecaCAT {
  "-_id": string; // "row-c3jv.nr8i-we7s",
  "-_uuid": string; // "00000000-0000-0000-E76C-2964F0695BFC",
  "-_position": string; // "0",
  "-_address": string; // "https://analisi.transparenciacatalunya.cat/resource/zzzz-zzzz/row-c3jv.nr8i-we7s",
  idequipament: string; // "10627897",
  alies: string; // "\nUniversitat Politècnica de Catalunya. Biblioteca del Campus Universitari de Manresa\n",
  nom: string; // "\nUniversitat Politècnica de Catalunya. Biblioteca del Campus Universitari de Manresa\n",
  categoria: string; // "Cultura|Biblioteques||",
  via: string; // "Av. Bases de Manresa, 7-11",
  cpostal: string; // "08242",
  poblacio: string; // "Manresa",
  codi_municipi: string; // "081136",
  comarca: string; // "Bages",
  telefon1?: string; // "93 877 72 21",
  utmx: string; // "402263.1",
  utmy: string; // "4621050.02",
  longitud: string; // "1.8247223226775613",
  latitud: string; // "41.7352559365019",
  email: string; // "biblioteca.bcum@upc.edu",
  data_modificacio: string; // "1632468374",
  propietats: any; // "\nAny de construcció|0|Any del cens|0|Superfície total en m2|0|Titularitat|Universitat\n",
  localitzacio?: string; // "POINT (1.8247223 41.735256)"
  web?: string; // { "-url": "http://www.bnc.cat", "-self-closing": "true" }
  tipus_via?: string; // "plta." | "av." | "pl." ...
  num?: string; // 2
  fax?: string; // "93 270 23 04"
}