// Generated by https://quicktype.io

export interface BibliotecaCAT {
  _attributes:      BibliotecaCATAttributes;
  idequipament:     TartuGecko;
  alies:            TartuGecko;
  nom:              TartuGecko;
  categoria:        TartuGecko;
  via:              TartuGecko;
  cpostal:          TartuGecko;
  poblacio:         TartuGecko;
  codi_municipi:    TartuGecko;
  comarca:          TartuGecko;
  telefon1?:        TartuGecko;
  utmx:             TartuGecko;
  utmy:             TartuGecko;
  longitud:         TartuGecko;
  latitud:          TartuGecko;
  email:            TartuGecko;
  data_modificacio: TartuGecko;
  propietats:       Propietat[];
  localitzacio?:    TartuGecko;
  web?:             Web;
  tipus_via?:       TartuGecko;
  num?:             TartuGecko;
  fax?:             TartuGecko;
}

export interface BibliotecaCATAttributes {
  _id:       string;
  _uuid:     string;
  _position: string;
  _address:  string;
}

export interface TartuGecko {
  _text: string;
}

export interface Propietat {
  "Any de construcció"?:                                                                                   string;
  "Any del cens"?:                                                                                         string;
  "Superfície total en m2"?:                                                                               string;
  Titularitat?:                                                                                            string;
  Accessibilitat?:                                                                                         string;
  Horari?:                                                                                                 string[];
  Observacions?:                                                                                           string;
  Oficina_Registre?:                                                                                       string;
  Accés?:                                                                                                  Accés;
  Especialitats?:                                                                                          string;
  "Horari d'estiu"?:                                                                                       string[];
  "Horari d'hivern"?:                                                                                      string[];
  Serveis?:                                                                                                string[];
  "Observacions horari hivern"?:                                                                           string;
  Període?:                                                                                                string;
  "Observacions horari estiu"?:                                                                            string;
  " cd.pndelsports@gencat.cat"?:                                                                           string;
  "L'horari d'atenció al públic és variable. Recomanem sempre concertar cita prèvia: Tel. 977 50 40 12 "?: string;
}

export enum Accés {
  CalDemanarCitaPrèviament = "Cal demanar cita prèviament",
  Lliure = "Lliure",
  Restringit = "Restringit",
}

export interface Web {
  _attributes: WebAttributes;
}

export interface WebAttributes {
  url: string;
}
